title: letsoon
url: letsoon.github.io

friends:
  - 
    title: 素锦
    href: https://www.isujin.com

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-coffeescript
  - jekyll-sass-converter


